apiVersion: skaffold/v4beta9
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
deploy:
  kubectl: {}
build:
  local:
    push: false
  # googleCloudBuild:
  #   projectId: k8lab-394905
  artifacts:
    - image: nightofserenity/auth
      # - image: us.gcr.io/k8lab-394905/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
